### ISSUE TITLE
exit status 255

### ISSUE THREAD

**Issue by mContext** [bclswl0827/v2ray-openshift#1]
V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/amd64)
A unified platform for anti-censorship.
main: failed to read config file: /etc/v2ray/config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to read config file at line 1 char 2 > invalid character 'o' in literal null (expecting 'u')

 > exit status 255

**Comment by k79e** [comment]
纯属配置文件错误 要不然就是贴了utf8的编码
自己在线测下json错误就知道了 没错误一般都是编码错误

**Comment by mContext** [comment]
> 纯属配置文件错误 要不然就是贴了utf8的编码
> 自己在线测下json错误就知道了 没错误一般都是编码错误

我没改过配置文件...
